name: Publish Release to Registry
on:
  release:
    types: [published]

jobs:
  npm_publish:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@master
      - uses: actions/setup-node@v2
        with:
          node-version: 'lts/*'
      - run: yarn
      - run: npm -g install typescript@4.9.5
      - run: whoami && node -v && ls -lah && tsc -v
      - run: npm -g install oclif @oclif/help
      - run: echo "//registry.npmjs.org/:_authToken=${{ secrets.NPMJS_PUBLISH_TOKEN }}" > .npmrc
      - run: npm --no-git-tag-version version ${{ github.event.release.tag_name }}
      - run: tsc -b
      - run: oclif manifest
      - run: ls -lah ./
      - run: npm publish --access public

  npm_test:
    needs: [npm_publish]

    runs-on: ubuntu-latest

    container:
      image: node:lts-alpine

    steps:
      - run: npm -g install @jahia/jcustomer-custom-event-checker@${{ github.event.release.tag_name }}
      - run: jcustomer-custom-event-checker help
      - run: jcustomer-custom-event-checker validateEvents --help

  docker:
    needs: [npm_test]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - name: Get release version
        id: get_version
        run: echo "RELEASE_VERSION=$(echo ${GITHUB_REF:10})" >> $GITHUB_ENV
      - name: Publish to Registry
        uses: elgohr/Publish-Docker-Github-Action@v5
        with:
          name: jahia/jcustomer-custom-event-checker
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_PASSWORD }}
          tags: 'latest,${{ env.RELEASE_VERSION }}'
